### ISSUE TITLE
Trying to get it up and running

### ISSUE THREAD

**Issue by mrtn** [borlak/cryptocoin_scrypt_stratum#1]
Hello,

Do you still support this repo?

I am trying to set this up.

But I do not exactly understand what to do whit this line in the installation guid.

edit work_manager.js and make sure it is doing AJAX requests to the correct location for your particular web server setup, search for get(

I have this in work_manager.js:

```
jQuery.get('/w', 'w=1', function(data) {
    if(data.length > 0) {
        ret = data.split("\n");
        if(ret.length == 2) {
            vals = ret[0];
            b = JSON.parse(ret[1]);
            updateWorkers({vals:vals,b:b});
        }
    }
});
```

I have this error:

http://mydomain.com/w?w=1 404 (Not Found)

Can you please advice?

Best regards

**Comment by borlak** [comment]
It's doing an AJAX "get" request to /w, so it's looking for a page on your website simply called "w".  Depending on how you have your web server running, you might rename this to w.php, ie:
jQuery.get('/w.php', 'w=1'...
