### ISSUE TITLE
Hash rate calculation

### ISSUE THREAD

**Issue by shoaibali** [borlak/cryptocoin_scrypt_stratum#3]
Hi,

After some configuration, I managed to get it going. However, how did you calculated the hash rate? 

I will be sending through a pull request for some minor changes to documentation and configuration.

Thanks,

Shoaib

**Comment by borlak** [comment]
It has been some time ago so I don't remember how I calculated it exactly.  However, it does look like it does some console logging (with debug on) every 3k iterations:
https://github.com/borlak/cryptocoin_scrypt_stratum/blob/master/worker/worker.js#L446
So you could get a rough estimate that way.

**Comment by shoaibali** [comment]
thanks for getting back so quickly @borlak . I am seeing the console message every 3K iterations. 

The pool I am connected to via stratum is not reporting my hash rate either. Therefore, I am left wondering how I can calculate it?

Would you remember the concept behind how the pools know about what hash rate the workers are working at? Is it part of the messaging that is happening over stratum+tcp?

What would be the formula to calculate estimated hash rate? i.e what does 3K iterations mean? ie it 3000 hashes? 

Would it be 3000 divided by time it took to complete 3000 iterations? it needs to be in kH/s

![scryp](https://user-images.githubusercontent.com/180494/34803414-0ca4762a-f6d8-11e7-8fe4-d38c150f9a7e.png)

**Comment by borlak** [comment]
Sorry, this is all really fuzzy to me as I haven't been developing in cryptocurrency for years :)  
I don't know how the pool would know your hashrate, since you, the client, are doing the hashing.  Maybe they can make estimates based on the difficulty and how often you submit "work".  

The iterations is roughly the # of hashes, yes.  There is more work being done than just hashing, but the hashing part (the scrypt function) is taking the vast majority of the time, so I just count every iteration as a "hash".  Your thoughts on taking the time between the 3k iterations would make sense in getting a rough kH/s

**Comment by shoaibali** [comment]
Brilliant, thank you so much @borlak . As a fellow developer I can completely symphatise with you.  

All these questions dont mean much and developing within crypto currencies especially using CPUs is worthless. I myself was just curious and wanted to learn. Subsequently contribute better documentation for others like me who may get curious. I feel more comfortable with php/javascript as technologies. I could have dug up answers myself but I have come to a realisation that it is not always quicker to ask the original author. As developers, most importantly humans - we churn out so much code that we cannot remember all intricate details of all the code we develop. I shall further investigate on how mining pools work out our hash rates.

I commend and thank you again for the effort you previously put in to open source this. Much apreciate it.

I am also greatful that you took a few moments to respond to my issue.

Cheers for pointing me in the right direction. Feel free to close this issue.
